=== netgroup-polito/frog4-configurable-vnf/configuration-agent/common/vnf_template_library/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "functional-capability": {
            "type": "string"
        },
        "expandable": {
            "type": "boolean"
        },
        "vnf-type": {
            "enum": [
                "virtual-machine-kvm",
                "docker",
                "native",
                "dpdk",
                "onos-application"
            ]
        },
        "uri-image-type": {
            "enum": [
                "local-file",
                "remote-file",
                "docker-registry"
            ]
        },
        "uri-image": {
            "type": "string"
        },
        "uri-yang": {
            "type": "string"
        },
        "memory-size": {
            "type": "number"
        },
        "root-file-system-size": {
            "type": "number"
        },
        "ephemeral-file-system-size": {
            "type": "number"
        },
        "swap-disk-size": {
            "type": "number"
        },
        "CPUrequirements": {
            "type": "object",
            "properties": {
                "platformType": {
                    "type": "string"
                },
                "socket": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "coreNumbers": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "ports": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "position": {
                        "type": "string",
                        "pattern": "^(([0-9]|[1-9][0-9]*)([-](([1-9]?[0-9]*)|N))?)$"
                    },
                    "label": {
                        "type": "string"
                    },
                    "min": {
                        "type": "string"
                    },
                    "ipv4-config": {
                        "type": "string"
                    },
                    "ipv6-config": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "technology": {
                        "enum": [
                            "vhost",
                            "usvhost",
                            "ivshmem"
                        ]
                    }
                },
                "required": [
                    "position",
                    "label",
                    "min",
                    "name"
                ],
                "additionalProperties": false
            }
        }
    },
    "required": [
        "vnf-type",
        "functional-capability",
        "uri-image-type",
        "memory-size",
        "CPUrequirements",
        "ports"
    ],
    "additionalProperties": false
}

=== netgroup-polito/frog4-configurable-vnf/docker/firewall/template.json
{
  "CPUrequirements": {
    "platformType": "x86",
    "socket": [
      {
        "coreNumbers": 1
      }
    ]
  },
  "ephemeral-file-system-size": 0,
  "name": "firewall",
  "functional-capability": "firewall_docker",
  "memory-size": 2048,
  "vnf-type": "docker",
  "uri-yang": "http://130.192.225.179:8081/yang/fw_cfg/",
  "uri-image-type": "docker-registry",
  "swap-disk-size": 0,
  "expandable": false,
  "ports": [
    {
      "name": "eth",
      "min": "1",
      "label": "management",
      "ipv4-config": "none",
      "position": "0-0",
      "ipv6-config": "none"
    },
    {
      "name": "eth",
      "min": "1",
      "label": "L2Port",
      "ipv4-config": "none",
      "position": "1-N",
      "ipv6-config": "none"
    }
  ],
  "root-file-system-size": 40,
  "uri-image": "firewall_config"
}
